<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class PermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('permissions')->delete();
        DB::table('permissions')->insert([
        [
            'id'=>1,
            'permission_name'=>'admin',
            'permission_module'=>'view',
            'permission'=>'admin-view',
            'created_at' => now(),
            'updated_at' =>  now(),
        ],
        [
            'id'=>2,
            'permission_name'=>'admin',
            'permission_module'=>'add',
            'permission'=>'admin-add',
            'created_at' => now(),
            'updated_at' =>  now(),
        ],
        [
            'id'=>3,
            'permission_name'=>'admin',
            'permission_module'=>'update',
            'permission'=>'admin-update',
            'created_at' => now(),
            'updated_at' =>  now(),
        ],
        [
            'id'=>4,
            'permission_name'=>'admin',
            'permission_module'=>'delete',
            'permission'=>'admin-delete',
            'created_at' => now(),
            'updated_at' =>  now(),
        ],
        [
            'id'=>5,
            'permission_name'=>'user',
            'permission_module'=>'view',
            'permission'=>'user-view',
            'created_at' => now(),
                'updated_at' =>  now(),
        ],
        [
            'id'=>6,
            'permission_name'=>'user',
            'permission_module'=>'add',
            'permission'=>'user-add',
            'created_at' => now(),
            'updated_at' =>  now(),
        ],
        [
            'id'=>7,
            'permission_name'=>'user',
            'permission_module'=>'update',
            'permission'=>'user-update',
            'created_at' => now(),
            'updated_at' =>  now(),
        ],
        [
            'id'=>8,
            'permission_name'=>'user',
            'permission_module'=>'delete',
            'permission'=>'user-delete',
            'created_at' => now(),
            'updated_at' =>  now(),
        ],
        [
            'id'=>9,
            'permission_name'=>'role',
            'permission_module'=>'view',
            'permission'=>'role-view',
            'created_at' => now(),
                'updated_at' =>  now(),
        ],
        [
            'id'=>10,
            'permission_name'=>'role',
            'permission_module'=>'add',
            'permission'=>'role-add',
            'created_at' => now(),
            'updated_at' =>  now(),
        ],
        [
            'id'=>11,
            'permission_name'=>'role',
            'permission_module'=>'update',
            'permission'=>'role-update',
            'created_at' => now(),
            'updated_at' =>  now(),
        ],
        [
            'id'=>12,
            'permission_name'=>'role',
            'permission_module'=>'delete',
            'permission'=>'role-delete',
            'created_at' => now(),
            'updated_at' =>  now(),
        ],
        [
            'id'=>13,
            'permission_name'=>'permission',
            'permission_module'=>'view',
            'permission'=>'permission-view',
            'created_at' => now(),
                'updated_at' =>  now(),
        ],
        [
            'id'=>14,
            'permission_name'=>'post',
            'permission_module'=>'view',
            'permission'=>'post-view',
            'created_at' => now(),
                'updated_at' =>  now(),
        ],
        [
            'id'=>15,
            'permission_name'=>'post',
            'permission_module'=>'show',
            'permission'=>'post-show',
            'created_at' => now(),
            'updated_at' =>  now(),
        ],
        [
            'id'=>16,
            'permission_name'=>'post',
            'permission_module'=>'delete',
            'permission'=>'post-delete',
            'created_at' => now(),
            'updated_at' =>  now(),
        ],
        [
            'id'=>17,
            'permission_name'=>'filter',
            'permission_module'=>'view',
            'permission'=>'filter-view',
            'created_at' => now(),
                'updated_at' =>  now(),
        ],
        [
            'id'=>18,
            'permission_name'=>'filter',
            'permission_module'=>'add',
            'permission'=>'filter-add',
            'created_at' => now(),
            'updated_at' =>  now(),
        ],
        [
            'id'=>19,
            'permission_name'=>'filter',
            'permission_module'=>'update',
            'permission'=>'filter-update',
            'created_at' => now(),
            'updated_at' =>  now(),
        ],
        [
            'id'=>20,
            'permission_name'=>'filter',
            'permission_module'=>'delete',
            'permission'=>'filter-delete',
            'created_at' => now(),
            'updated_at' =>  now(),
        ],
        [
            'id'=>21,
            'permission_name'=>'interest',
            'permission_module'=>'view',
            'permission'=>'interest-view',
            'created_at' => now(),
            'updated_at' =>  now(),
        ],
        [
            'id'=>22,
            'permission_name'=>'interest',
            'permission_module'=>'add',
            'permission'=>'interest-add',
            'created_at' => now(),
            'updated_at' =>  now(),
        ],
        [
            'id'=>23,
            'permission_name'=>'interest',
            'permission_module'=>'update',
            'permission'=>'interest-update',
            'created_at' => now(),
            'updated_at' =>  now(),
        ],
        [
            'id'=>24,
            'permission_name'=>'interest',
            'permission_module'=>'delete',
            'permission'=>'interest-delete',
            'created_at' => now(),
            'updated_at' =>  now(),
        ],
        [
            'id'=>25,
            'permission_name'=>'spot',
            'permission_module'=>'view',
            'permission'=>'spot-view',
            'created_at' => now(),
                'updated_at' =>  now(),
        ],
        [
            'id'=>26,
            'permission_name'=>'spot',
            'permission_module'=>'add',
            'permission'=>'spot-add',
            'created_at' => now(),
            'updated_at' =>  now(),
        ],
        [
            'id'=>27,
            'permission_name'=>'spot',
            'permission_module'=>'update',
            'permission'=>'spot-update',
            'created_at' => now(),
            'updated_at' =>  now(),
        ],
        [
            'id'=>28,
            'permission_name'=>'spot',
            'permission_module'=>'delete',
            'permission'=>'spot-delete',
            'created_at' => now(),
            'updated_at' =>  now(),
        ],
        [
            'id'=>29,
            'permission_name'=>'event',
            'permission_module'=>'view',
            'permission'=>'event-view',
            'created_at' => now(),
                'updated_at' =>  now(),
        ],
        [
            'id'=>30,
            'permission_name'=>'event',
            'permission_module'=>'add',
            'permission'=>'event-add',
            'created_at' => now(),
            'updated_at' =>  now(),
        ],
        [
            'id'=>31,
            'permission_name'=>'event',
            'permission_module'=>'update',
            'permission'=>'event-update',
            'created_at' => now(),
            'updated_at' =>  now(),
        ],
        [
            'id'=>32,
            'permission_name'=>'event',
            'permission_module'=>'delete',
            'permission'=>'event-delete',
            'created_at' => now(),
            'updated_at' =>  now(),
        ],
        [
            'id'=>33,
            'permission_name'=>'page',
            'permission_module'=>'view',
            'permission'=>'page-view',
            'created_at' => now(),
                'updated_at' =>  now(),
        ],
        [
            'id'=>34,
            'permission_name'=>'page',
            'permission_module'=>'add',
            'permission'=>'page-add',
            'created_at' => now(),
            'updated_at' =>  now(),
        ],
        [
            'id'=>35,
            'permission_name'=>'page',
            'permission_module'=>'update',
            'permission'=>'page-update',
            'created_at' => now(),
            'updated_at' =>  now(),
        ],
        [
            'id'=>36,
            'permission_name'=>'page',
            'permission_module'=>'delete',
            'permission'=>'page-delete',
            'created_at' => now(),
            'updated_at' =>  now(),
        ],
        [
            'id'=>37,
            'permission_name'=>'group',
            'permission_module'=>'view',
            'permission'=>'group-view',
            'created_at' => now(),
                'updated_at' =>  now(),
        ],
        [
            'id'=>38,
            'permission_name'=>'group',
            'permission_module'=>'show',
            'permission'=>'group-show',
            'created_at' => now(),
            'updated_at' =>  now(),
        ],
        [
            'id'=>39,
            'permission_name'=>'checkin post',
            'permission_module'=>'view',
            'permission'=>'checkin-post-view',
            'created_at' => now(),
                'updated_at' =>  now(),
        ],
        [
            'id'=>40,
            'permission_name'=>'checkin post',
            'permission_module'=>'show',
            'permission'=>'checkin-post-show',
            'created_at' => now(),
            'updated_at' =>  now(),
        ],
        [
            'id'=>41,
            'permission_name'=>'checkin post',
            'permission_module'=>'delete',
            'permission'=>'checkin-post-delete',
            'created_at' => now(),
            'updated_at' =>  now(),
        ],
        [
            'id'=>42,
            'permission_name'=>'group post',
            'permission_module'=>'view',
            'permission'=>'group-post-view',
            'created_at' => now(),
                'updated_at' =>  now(),
        ],
        [
            'id'=>43,
            'permission_name'=>'group post',
            'permission_module'=>'show',
            'permission'=>'group-post-show',
            'created_at' => now(),
            'updated_at' =>  now(),
        ],
        [
            'id'=>44,
            'permission_name'=>'group post',
            'permission_module'=>'delete',
            'permission'=>'group-post-delete',
            'created_at' => now(),
            'updated_at' =>  now(),
        ],
        [
            'id'=>45,
            'permission_name'=>'spot post',
            'permission_module'=>'view',
            'permission'=>'spot-post-view',
            'created_at' => now(),
                'updated_at' =>  now(),
        ],
        [
            'id'=>46,
            'permission_name'=>'spot post',
            'permission_module'=>'show',
            'permission'=>'spot-post-show',
            'created_at' => now(),
            'updated_at' =>  now(),
        ],
        [
            'id'=>47,
            'permission_name'=>'spot post',
            'permission_module'=>'delete',
            'permission'=>'spot-post-delete',
            'created_at' => now(),
            'updated_at' =>  now(),
        ],
        [
            'id'=>48,
            'permission_name'=>'review',
            'permission_module'=>'view',
            'permission'=>'review-view',
            'created_at' => now(),
            'updated_at' =>  now(),
        ],
        [
            'id'=>49,
            'permission_name'=>'review',
            'permission_module'=>'show',
            'permission'=>'review-show',
            'created_at' => now(),
            'updated_at' =>  now(),
        ],
        [
            'id'=>50,
            'permission_name'=>'review',
            'permission_module'=>'delete',
            'permission'=>'review-delete',
            'created_at' => now(),
            'updated_at' =>  now(),
        ],
        [
            'id'=>51,
            'permission_name'=>'expertise',
            'permission_module'=>'view',
            'permission'=>'expertise-view',
            'created_at' => now(),
            'updated_at' =>  now(),
        ],
        [
            'id'=>52,
            'permission_name'=>'expertise',
            'permission_module'=>'add',
            'permission'=>'expertise-add',
            'created_at' => now(),
            'updated_at' =>  now(),
        ],
        [
            'id'=>53,
            'permission_name'=>'expertise',
            'permission_module'=>'update',
            'permission'=>'expertise-update',
            'created_at' => now(),
            'updated_at' =>  now(),
        ],
        [
            'id'=>54,
            'permission_name'=>'expertise',
            'permission_module'=>'delete',
            'permission'=>'expertise-delete',
            'created_at' => now(),
            'updated_at' =>  now(),
        ],
        [
            'id'=>55,
            'permission_name'=>'cms',
            'permission_module'=>'view',
            'permission'=>'cms-view',
            'created_at' => now(),
            'updated_at' =>  now(),
        ],
        [
            'id'=>56,
            'permission_name'=>'cms',
            'permission_module'=>'update',
            'permission'=>'cms-update',
            'created_at' => now(),
            'updated_at' =>  now(),
        ],
        [
            'id'=>57,
            'permission_name'=>'cms-detail',
            'permission_module'=>'view',
            'permission'=>'cms-detail-view',
            'created_at' => now(),
            'updated_at' =>  now(),
        ],
        [
            'id'=>58,
            'permission_name'=>'cms-detail',
            'permission_module'=>'add',
            'permission'=>'cms-detail-add',
            'created_at' => now(),
            'updated_at' =>  now(),
        ],
        [
            'id'=>59,
            'permission_name'=>'cms-detail',
            'permission_module'=>'update',
            'permission'=>'cms-detail-update',
            'created_at' => now(),
            'updated_at' =>  now(),
        ],
        [
            'id'=>60,
            'permission_name'=>'cms-detail',
            'permission_module'=>'delete',
            'permission'=>'cms-detail-delete',
            'created_at' => now(),
            'updated_at' =>  now(),
        ],
        ]);
    }
}
